export { default as authRoutes } from './auth.routes'
export { default as companyRoutes } from './company.routes'
export { default as userRoutes } from './user.routes'
export { default as roleRoutes } from './role.routes'
export { default as permissionRoutes } from './permission.routes'